### ISSUE TITLE
Makefile complie errors

### ISSUE THREAD

**Issue by mbeltagy** [rcqls/jl4rb#2]
The `Makefile` does not seem to make use of `JULIA_DIR`. 

I get compilation errors related ton including `julia.h`. Looking at the `Makefile` is seems that the include is hard-coded for a standard julia 0.5 OSx install.

**Comment by rcqls** [comment]
@mbeltagy  JULIA_DìR is used in `jl4rb/lib/jl4rb/jl2rb_init.rb` and in `jl4rb/ext/extconf.rb`. On my computer `JULIA_DIR=/Applications/Julia-0.6.app/Contents/Resources/julia` .
Be careful, the`Makefile` is automatically generated from the `extconf.rb` at installation.

**Comment by mbeltagy** [comment]
In the `Makefile` there are several static directory references, which would make it impossible to compile on anything other than Julia 0.5 on OS X. 
See for example
https://github.com/rcqls/jl4rb/blob/c3727606b7153c95802b0f8710304966afec1454/ext/jl4rb/Makefile#L14

https://github.com/rcqls/jl4rb/blob/c3727606b7153c95802b0f8710304966afec1454/ext/jl4rb/Makefile#L16

https://github.com/rcqls/jl4rb/blob/c3727606b7153c95802b0f8710304966afec1454/ext/jl4rb/Makefile#L86

https://github.com/rcqls/jl4rb/blob/c3727606b7153c95802b0f8710304966afec1454/ext/jl4rb/Makefile#L81

**Comment by rcqls** [comment]
As I told you when you install this gem `gem install jl4rb` the `Makefile` has to be regenerated. So the `Makefile` in this repo is not considered since the `Makefile` is not embedded in the `jl4rb.gem`.

**Comment by mbeltagy** [comment]
I tried many times and failed and I can not figure out what the problem is
When I run 
`gem install jl4rb`

I get 
```bash
Building native extensions.  This could take a while...
ERROR:  Error installing jl4rb:
	ERROR: Failed to build gem native extension.

    current directory: /home/usr/.rvm/gems/ruby-2.3.0/gems/jl4rb-0.0.10/ext/jl4rb
/home/usr/.rvm/rubies/ruby-2.3.0/bin/ruby -r ./siteconf20180501-10439-1f6ipst.rb extconf.rb
creating Makefile

current directory: /home/usr/.rvm/gems/ruby-2.3.0/gems/jl4rb-0.0.10/ext/jl4rb
make "DESTDIR=" clean

current directory: /home/usr/.rvm/gems/ruby-2.3.0/gems/jl4rb-0.0.10/ext/jl4rb
make "DESTDIR="
compiling jl4rb.c
jl4rb.c:7:19: fatal error: julia.h: No such file or directory
 #include "julia.h"
                   ^
compilation terminated.
make: *** [jl4rb.o] Error 1

make failed, exit code 2
```
The makefile generated at 
`/home/usr/.rvm/gems/ruby-2.3.0/gems/jl4rb-0.0.10/ext/jl4rb/Makefile` has no references to `JULIA_DIR` or its contents. 

After  a bit of digging, I noticed that 
https://github.com/rcqls/jl4rb/blob/c3727606b7153c95802b0f8710304966afec1454/ext/jl4rb/extconf.rb#L6-L10

Makes no references to  `JULIA_DIR`. Only if you are on none linux platform would this used. 
There is an assumption of fixed install location for Julia, which is not true in my case.

**Comment by rcqls** [comment]
Could you check where is located the include julia dir and the lib julia dir on your computer ?
In my install, I only assume `/usr/include/RUBY_PLATFORM/julia` and   `/usr/lib/RUBY_PLATFORM/julia` which could not be valid anymore with last linux build....

**Comment by mbeltagy** [comment]
On my machine it is at required headers are at `JULIA_DIR/src/`
I happen to like to build my julia from source. But the file structure also holds for other binary installs.
In the pull request, I have taken out the `linux` specific bits and it seems to work just fine now. 
Also I ran into compile errors with `jl_init` taking arguments, so I had to excise bit that do that. 
It now work fine my linux machine.
